ibexa.platform.product_catalog:
    resource: '@IbexaProductCatalogBundle/Resources/config/routing.yaml'

ibexa.platform.product_catalog.admin:
    resource: '@IbexaProductCatalogBundle/Resources/config/routing_admin.yaml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'
