ibexa.scheduler:
    resource: '@IbexaSchedulerBundle/Resources/config/routing.yaml'

ibexa.scheduler.rest:
    resource: '@IbexaSchedulerBundle/Resources/config/routing_rest.yaml'
    prefix: '%ez_systems_date_based_publisher_rest_prefix%'
