ezplatform.ee.date_based_publisher:
    resource: '@IbexaSchedulerBundle/Resources/config/routing.yaml'

ezplatform.ee.date_based_publisher_rest:
    resource: '@IbexaSchedulerBundle/Resources/config/routing_rest.yaml'
    prefix: '%ez_systems_date_based_publisher_rest_prefix%'
