parameters:
    siso_core.default.logo_image: /bundles/ibexacommerceeshop/img/logo.png
    siso_core.admin.logo_image: /bundles/ibexacommerceeshop/img/logo.png
    siso_core.default.invoice_logo: /bundles/ibexacommerceeshop/img/invoice_logo.png
    siso_core.default.email_header: /bundles/ibexacommerceeshop/img/email-header.png


    siso_order_history.default.use_local_documents: true

    # Default settings for Commerce - will be overriden by backend config!
    siso_price.default.price_service_chain.product_list:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.product_detail:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.slider_product_list:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.basket:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.basket_variant:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.stored_basket:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.wish_list:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.quick_order:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.quick_order_line_preview:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.comparison:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.search_list:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
    siso_price.default.price_service_chain.bestseller_list:
        - Ibexa\Bundle\Commerce\PriceEngine\Service\ShopPriceProvider
